src/IdentityServer/Controllers/PasswordRecoveryController.cs
using ApplicationCore;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using IdentityServer.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace IdentityServer.Controllers
{
    public class PasswordRecoveryController : Controller
    {
        readonly UserManager<ApplicationUser> _userManager;
        readonly IEmailSender _emailSender;
        readonly IIdentityApiConfirguration _options;

        public PasswordRecoveryController(
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender,
            IOptions<IdentityApiConfirguration> options)
        {
            _userManager = userManager;
            _emailSender = emailSender;
            _options = options.Value;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Submitted = false;
            ViewBag.ReturnUrl = _options.SpaSpellingClientBaseUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RequestPasswordResetDto dto)
        {
            ViewBag.ReturnUrl = _options.SpaSpellingClientBaseUrl;
            if (this.ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(dto.Emailaddress.ToLower());
                if(user != null)
                {
                    var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                    var host = this.Request.Host.Value.Replace("[", string.Empty).Replace("]", string.Empty);
                    var url = $"{this.Request.Scheme}://{host}/PasswordRecovery/ResetPassword?token={WebUtility.UrlEncode(token)}";

                    var message = $"A password reset has be requested.<br /> <a href=\"{url}\">click here to reset your password.</a>";
                    await _emailSender.SendEmailAsync(user.Email, "College Spelling App Password Reset", message);
                }
            }
            ViewBag.Submitted = true;
            return View();
        }

        [HttpGet]
        public IActionResult ResetPassword(string token)
        {
            RequestPasswordChangeDto dto = new RequestPasswordChangeDto
            {
                Token = token
            };
            return View(dto);
        }


        [HttpPost]
        public async Task<IActionResult> ResetPassword(RequestPasswordChangeDto dto)
        {
            if (!this.ModelState.IsValid)
            {
                return View(dto);
            }
            var user = await _userManager.FindByEmailAsync(dto.Emailaddress.ToLower());
            if (user != null)
            {
                var result = await _userManager.ResetPasswordAsync(user, dto.Token, dto.NewPassword);

                if (!result.Succeeded)
                {
                    dto.IdentityResult = result;
                    return View(dto);
                }
            }
            else
            {
                ModelState.AddModelError("Emailaddress", "You have not entered your email address correctly.");
                return View(dto);
            }

            ViewBag.ReturnUrl = _options.SpaSpellingClientBaseUrl;
            return View("PasswordWasReset");
        }
    }
}

src/IdentityServer/Views/PasswordRecovery/Index.cshtml
@model IdentityServer.Models.RequestPasswordResetDto

<div class="welcome-page">
    <div class="row page-header">
        <div class="col-sm-10">
            <h1>
                <img class="icon" src="~/icon.jpg">
                Password reset
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            @if (ViewBag.Submitted == false)
            {
                using (Html.BeginForm("Index", "PasswordRecovery", FormMethod.Post))
                {
                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        @Html.TextBoxFor(m => m.Emailaddress, new { @class = "form-control" })
                        @*<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">*@
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                }

            } else
            {
                <p>An email has been sent for you to reset your password.</p>
                <a href="@ViewBag.ReturnUrl">Return back to the spelling app.</a>
            }
        </div>
    </div>
</div>

src/IdentityServer/Views/PasswordRecovery/PasswordWasReset.cshtml
@{
    ViewData["Title"] = "PasswordWasReset";
}

<h2>Your password has been reset</h2>

<a href="@ViewBag.ReturnUrl">Return back to the spelling app.</a>

src/IdentityServer/Views/PasswordRecovery/ResetPassword.cshtml
@model IdentityServer.Models.RequestPasswordChangeDto

@{
    ViewData["Title"] = "ResetPassword";
}

<h2>Reset Your Password</h2>
<hr />
<p>
    Your new password must have a minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character:
</p>
@if (Model.IdentityResult != null && !Model.IdentityResult.Succeeded)
{
<div class="alert alert-danger" role="alert">
    @foreach (var error in Model.IdentityResult.Errors)
    {
        <p>
            @error.Description
        </p>
    }
</div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="ResetPassword">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Emailaddress" class="control-label"></label>
                <input asp-for="Emailaddress" class="form-control" />
                <span asp-validation-for="Emailaddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPassword" class="control-label"></label>
                <input type="password" asp-for="NewPassword" class="form-control" />
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
            @Html.HiddenFor(m => m.Token)
        </form>
    </div>
</div>